version: '3.4'

services:
  elegantstringencoderwebapi:
    image: ${DOCKER_REGISTRY-}elegantstringencoderwebapi:1.0.3
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
     - "7286:80"
    networks:
     - hyperlink
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:80

  angular-app:
    image: ${DOCKER_REGISTRY-}angular-app:1.0.2
    ports:
     - "4200:80"
    depends_on:
     - elegantstringencoderwebapi
    networks:
     - hyperlink
    environment:
      - PROXY_PASS=http://web/

networks:
    hyperlink:
       driver: bridge